main/urls.py
from django.urls import path
from . import views

app_name="main"
urlpatterns = [
    path('home/', views.home, name='home'),
    path('changepass/', views.changepass, name='changepass'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),

    path('order/', views.order, name='order'),
    path('paypal/', views.paypal, name='paypal'),

    path('blog/', views.blog, name='blog'),
    path('blog/<int:id>/', views.blog_i, name='blog_i'),
    path('blog/add_blog/', views.add_blog, name='add_blog'),
    

]

webdemo/urls.py
from django.contrib import admin
from django.urls import path, include

app_name="main"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    # path('',include('info.urls')),
]

main/models.py
from django.db import models
from sqlalchemy import false

class User(models.Model):
    email = models.CharField(max_length=100)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.email

class Orders(models.Model):
    customer_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_orders')
    price = models.CharField(max_length=30)
    note = models.CharField(max_length=500)
    def __str__(self):
        return self.customer_id
    
class Blog(models.Model):
    # """Blog Post"""
    title=models.CharField(max_length=100, null=false)
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog')
    description = models.CharField(max_length=500,null=True)
    content=models.TextField()
    date =models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    #  """ comment"""
    id_blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    comment = models.CharField(max_length=500,null=false)
    date = models.DateTimeField(auto_now_add=True)
    

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User, Blog, Comment
from django.contrib import messages

# home
def home(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user': current_user}  
        return render(request, 'main/home.html', param)
    else:
       return redirect('main:login')

# signup
def signup(request):
    if request.method == "POST":
        email = request.POST.get('email')
        uname = request.POST.get('name')
        pwd = request.POST.get('pwd')
        repwd=request.POST.get('repwd')

        if User.objects.filter(username=uname).count()>0:
           return render(request, 'main/signup.html', {'error_message': 'Username already exists'})
        if pwd!=repwd:
            return render(request, 'main/signup.html', {'error_message1': 'password and repassword not same'})
        if email=='':
            return render(request, 'main/signup.html', {'error_message2': 'email cannot be blank'})
        if uname=='':
            return render(request, 'main/signup.html', {'error_message2': 'name cannot be blank'})
        if pwd=='':
            return render(request, 'main/signup.html', {'error_message2': 'password cannot be blank'})
        if repwd=='':
            return render(request, 'main/signup.html', {'error_message2': 'password cannot be blank'})

        else:
            user = User( email = email, username = uname, password = pwd )
            user.save()
            return redirect('main:login')
    else:
        return render(request,'main/signup.html')

# login
def login(request):
    if request.method == "POST":
        uname = request.POST.get('uname')
        pwd = request.POST.get('pwd')
        check_user = User.objects.filter(username=uname, password =pwd)
        if check_user:
            request.session['user'] = uname
            param = {'current_user': uname}
            return redirect('main:home')
        else:
            return render(request, 'main/login.html', {'error_message':'Please enter valid Username or Password'})

    return render(request, 'main/login.html')

#chang password
def changepass(request):
    current_user = request.session['user']
    param = {'current_user': current_user}
    if request.method == "POST":
        oldpass = request.POST.get('oldpass')
        newpass = request.POST.get('newpass')
        repass = request.POST.get('repass')
        check_user = User.objects.filter(username=current_user, password =oldpass)
        
        if newpass==repass:
            if check_user:
                new_pass=User.objects.get(username=current_user)
                new_pass.password=newpass
                new_pass.save()
                return redirect('main:home')
            else:
                return render(request, 'main/changepass.html', {'error_message':'old password incorrect'})

        else:
            return render(request, 'main/changepass.html', {'error_message':'password and repassword not same'})

    return render(request, 'main/changepass.html', param)

# logout
def logout(request):
    try:
        del request.session['user']
    except:
        return redirect('main:login')
    return redirect('main:login')

def blog(request):
    current_user = request.session['user']
    param = {'current_user': current_user}
    if 'user' in request.session:
        current_user = request.session['user']
        blogs = Blog.objects.order_by('-date')[:5]
        param = {'blogs':blogs,
        'current_user': current_user}
        return render(request, 'main/blog.html', param)
    else:
        return   redirect('main:home')
    

def blog_i(request,id):
    if 'user' in request.session:
        current_user = request.session['user']
        
        blog = Blog.objects.get(pk=id)
        comments = blog.comments.all().order_by('-date')[:10]
        param = {'comments':comments,'blog':blog,'current_user': current_user,}
        if request.method == "POST":
            _author=User.objects.get(username=current_user)
            _comment=request.POST.get('comment')
            comment_new = Comment(id_blog=blog, author = _author, comment = _comment)
            comment_new.save()
        return render(request, 'main/blog_i.html', param)
    else:
        return   redirect('main:login')


def add_blog(request):
    current_user = request.session['user']
    param = {'current_user': current_user}
    _author = User.objects.get(username=current_user)
    if request.method == "POST":
        _title = request.POST.get('title')
        _description = request.POST.get('description')
        _content=request.POST.get('content')
        if _title =='':
            return render(request,param,'main/add_blog.html', {'error_message': ' The title is not empty. '})
        else:
            blog = Blog(title =_title,author=_author, description = _description,content=_content )
            blog.save()
            return redirect('main:blog')
    else:
        return render(request,'main/add_blog.html',param)

# Pay migration
def paypal(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user': current_user}
        return render(request, 'main/paypal.html',param)
    else:
        return redirect('main:login')

# Order migration
def order(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user': current_user}
        return render(request, 'main/order.html',param)
    else:
        return redirect('main:login')
    

main/templates/main/chatbox01.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}
    <h2></h2>
     {% if error_message %}
          <div class="alert alert-primary" role="alert">
            {{error_message}}
          </div>
    {% endif %}
    <h1>  </h1>
    
   
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}
{% load staticfiles %}


{% block body %}
<!-- CSS -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static  'cloudflare.css' %}">
<link rel="stylesheet" href="{% static  'home4.css' %}">
<link rel="stylesheet" href="{% static  'base.css' %}">
<!-- END CSS -->
<div class="page side-collapse-container my-migration-page">
  <div class="container">
      <div class="row">
          <div class= "col-md-12 text-center align-self-center">
             <h1>START YOUR MIGRATION HERE!</h1>
          </div>
       </div>


      <div class="row">
          <div class="  col-md-6" >
              <div class="  col-support text-center">
           
                  <span class="automated-migration " >
                      <img src="https://app.shopping-cart-migration.com//images/automated-migration.png" >
                  </span>
      
                  <h4 class = "text-center">Follow the migration Wizard</h4>
                  
                      <div class="col-xs-10 col-xs-offset-1">
                          <h5 class ="text-center"><strong>What do I need to migrate?</strong></h5>
                          <ul class="my-migration-list list-unstyled text-center" >
                              <li> Source and Target carts installed and available online</li>
                              <li> Admin access to your Source and Target shopping carts</li>
                              <li> FTP Access - in case either/both carts are open source</li>
                          </ul>
                      </div>

                  <div class="cta text-center">
                      <a class="btn btn-md btn-success"
                      href="https://app.shopping-cart-migration.com/migrations/wizard/create">Start Free Demo                        </a>
                  </div>
              </div>
          </div>

          <div class=" col-md-6 ">
            <div class=" col-support text-center">
              <span class="assisted-migration">
                <img src="https://app.shopping-cart-migration.com//images/assisted-migration.png" >
              </span>
                <h4>Let Cart2Cart Team assist you!</h4>
                <div class="col-xs-10 col-xs-offset-1">
                  <h5><strong>Need some help to perform migration?</strong></h5>
                  <p>If there are any difficulties or you’re just too busy to through the migration wizard - our team of highly-skilled experts is always ready to give you a hand of help.</p>
                </div>
                  <div class="cta text-center">
                    <a href="javascript: void(0);" class="btn btn-md btn-primary" onclick="Intercom('show'); return false;">Get Assisted Migration                        </a>
                  </div>
                </div>
            </div>
          </div>
      

          <div class="row">
         
              <div class="card col-sm-12">
                  <div class=" col-estimate">
                      <div class="text-center">
                          <img src="https://app.shopping-cart-migration.com//images/estimate-price.png" alt="Estimate Price">
                          <p class="estimate-title">Calculate your migration price</p>
                          <p>Enter the number of data entities - products, customers and orders from your current store into the
                              Migration Estimator to see how much your migration will cost.</p>
                          <small>Learn how to check the number of data entities in your store <a target="_blank" href="https://www.shopping-cart-migration.com//faq/1-general-questions/294-how-to-check-the-number-of-entities-on-my-current-store">here</a>.</small>
                          <a href="https://app.shopping-cart-migration.com/estimation-page" class="btn btn-md btn-warning">Get Estimates</a>
                      </div>
                  </div>
              </div>
 
          </div>
      
  </div>
</div> 



<!-- <div class="home_page">
  <div class="header_home">
    <img
      src="https://scontent.fhan2-2.fna.fbcdn.net/v/t1.6435-9/170502150_285682159813495_1331339524602775949_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=174925&_nc_ohc=XsO9eIhAd2oAX8of4P6&_nc_ht=scontent.fhan2-2.fna&oh=00_AT-J73rmemjheVXH4ftFZZdz3-CQooLSESYD8VBJ7CoBPg&oe=6283CE61"
      alt="">
    <h1>Duy Hiệu</h1>
    <br>
  </div>
  <div class="body_home">
    <div class="home_side"></div>
    <div class="home_content">
      <h1>Contact information</h1>
      <ul>
        <li><i class="fa fa-calendar"></i>: September 12, 1998</li><br>
        <li><i class="fa fa-phone"></i>: 0947983316</li><br>
        <li><i class="fa fa-mail-forward"></i>: hieuduyth98@gmail.com</li><br>
        <li><i class="fa fa-link"></i>: https://duyhieu12.pythonanywhere.com/</li><br>
        <li><i class="fa fa-globe"></i>: Hanoi, Vietnam</li><br>
        <li><i class="fa fa-intersex"></i>: Male</li><br>
      </ul>
      <br>
      <h1>Objective</h1>
      <h3>Short-term goal:</h3>
      <ul>
        <li>+ Improve your level, learn and gain more experience</li> <br>
        <li>+ Training attitude and working spirit in a thriving IT environment</li>
      </ul>
      <h3>Long-term goals:</h3>
      <ul>
        <li>+ Become a Full Stack python Web
          programmer, working in a dynamic and
          professional environment. Bring value to teams
          and businesses</li> <br>
        <li>+ Develop your own products as well as try new
          positions</li>
      </ul>
      <br>
      <h1>Interests</h1>
      <li>I like jogging and badminton</li>
      <br>
    </div>

    <div class="home_content">
      <h1>Skills</h1>
      <h3>Database:</h3>
      <ul>
        <li>MySQL, SQL server</li>
      </ul>
      <h3>Python:</h3>
      <ul>
        <li>+ Python core, OOP, Functional Programming</li><br>
        <li>+ Web programming with Django</li><br>
        <li>+ Rest programming with Flask</li>
      </ul>
      <h3>Front-end:</h3>
      <ul>
        <li>HTML, CSS, JavaScript, Bootstrap</li>
      </ul>
      <h3>Project Process:</h3>
      <ul>
        <li>Coding, Testing, Deploying, Git</li>
      </ul>
      <h3>IDE:</h3>
      <ul>
        <li>SQL Workbench, Visual Studio Code</li>
      </ul><br>

      <h1>Projects</h1>
      <h3>Self-introduction website | March 2022 - April 2022</h3>
      <ul>
        <li>+ Project description: Introduce yourself, some articles about
          health, entertainment with basic games and music</li> <br>
        <li> + Number of members: 1</li><br>
        <li>+ Job position: Full-stack programmer</li><br>
        <li>+ Roles in the project: Front-End code, Back-End code, Design,
          Testing, Deploying to pythonanywhere.com</li><br>
        <li>+ Technology used: Django framework, HTML/CSS/JS</li>
      </ul><br>

      <h1>Education</h1>
      <h3>HANOI UNIVERSITY OF PHARMACY | OCT 2016 - MAY 2021</h3>
      <ul>
        <li>Specialization: Pharmaceutical economic management</li>
      </ul><br>
      <h1>Certifications</h1>
      <ul>
        <li>2021: Course: Python 01 (Python full-stack )VTI ACADEMY</li><br>
        <li>Duration: 6 months</li>
      </ul><br>

    </div>

    <div class="home_side"></div>

  </div>
</div> -->

{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block title %} Log In {% endblock %}

{% block body %}
<!-- CSS -->
{% load static %}
<!-- <link rel="stylesheet" href="{% static 'base.css' %}"> -->
<link rel="stylesheet" href="https://cdn.rawgit.com/ntvanank1250/css_wev_demo/main/login.css">
<!-- END CSS -->

<div class="col-md-12 text-center align-self-center " >
  <br>
    <h1 class="panel-heading" id="sign-in">Log In</h1>
    <br>
    <h4 class="panel-heading">New to MYWEBSITE?  <a href="{% url 'main:signup' %}">Create an account.</a></h4>
    <div style="    font-weight: 400;    font-size: 15px;    margin: 0px 55px;    font-weight: bo;"> (*)You're about to experience a stress-free, quick & accurate migration. Just log in!</div>
    {% if error_message %}
    <div class="alert alert-primary" role="alert">
      {{error_message}}
    </div>
    {% endif %}
    <div class="col-md-12 text-center align-self-center " >

    </div>
    <form method="POST" class="form-horizontal">
      {% csrf_token %}
      <br><br>
      <div class="form-group row ">
        <div class="col-md-6 text-right"><label for="email">Email:</label></div>
        <div class="col-md-6 text-left"><input type="text" name="email" placeholder="Your email"></div>
        <br>
      </div>
      <div class="form-group row">
        <div class="col-md-6 text-right"><label for="password">Password:</label></div>
        <div class="col-md-6 text-left"><input type="password" name="pwd" placeholder="Password"></div>
        <br>
      </div>
      <br>
      <div class="form-group button-panel">
        <div class="" style="text-align: center;">
            <button type="submit" name="submit" class="web-button web-button-default signin" style="padding: 0 50px">
                Log In
            </button>
        </div>
    </div>
    </form>
  </div>
  <div class ="hidden_if_phone">
    <br>
    <br>

    <br>
    <br>
    <br>
    <br>

  </div>
<div class="col-xs-12 text-center small">
    <label>* By signing in, you agree to our <a href="https://litextension.com/terms-conditions.html">Terms and Conditions</a>, <a href="https://litextension.com/privacy-policy.html">Private Policy</a>, <a href="https://litextension.com/gdpr-compliance.html">GDPR Compliance</a> and to receive LitExtension emails & updates of the migration process.</label>
</div>

{% endblock %}

main/templates/main/paypal.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>
    <div id = x>
     <!-- PAYPAL BUTTONS HERE  -->
      <!-- Set up a container element for the button -->
      <div id="paypal-button-container"></div>

      <!-- Include the PayPal JavaScript SDK -->
      <script src="https://www.paypal.com/sdk/js?client-id=AdrWcHwIT6IOAzjztFbaBXiIIvRstEZDi_Z1iIYLhY7L-dRasUbImr4tFm4FYRfTDpVPPbSBjQSLd04W&currency=USD"></script>
  
      <script>
          // Render the PayPal button into #paypal-button-container
          paypal.Buttons({
  
              // Set up the transaction
              createOrder: function(data, actions) {
                  return actions.order.create({
                      purchase_units: [{
                          amount: {
                              value: '88.44'
                          }
                      }]
                  });
              },
  
              // Finalize the transaction
              onApprove: function(data, actions) {
                  return actions.order.capture().then(function(orderData) {
                      // Successful capture! For demo purposes:
                      console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                      var transaction = orderData.purchase_units[0].payments.captures[0];
                      alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
  
                      // Replace the above to show a success message within this page, e.g.
                      // const element = document.getElementById('paypal-button-container');
                      // element.innerHTML = '';
                      // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                      // Or go to another URL:  actions.redirect('thank_you.html');
                  });
              }
  
  
          }).render('#paypal-button-container');
      </script>
      </div>
</body>

main/templates/main/signup.html
{% extends 'main/base.html' %}
{% block title %} Signup {% endblock %}

{% block body %}
{% load static %}
<!-- CSS -->
{% load static %}
<!-- <link rel="stylesheet" href="{% static 'base.css' %}"> -->
<link rel="stylesheet" href="https://cdn.rawgit.com/ntvanank1250/css_wev_demo/main/login.css">
<!-- END CSS -->

<div class="col-md-12 text-center align-self-center " >
  <br>
    <h1 class="panel-heading" id="sign-in">Log In</h1>
    <br>
    <h4 class="panel-heading">New to MYWEBSITE?  <a href="{% url 'main:signup' %}">Create an account.</a></h4>
    <div style="    font-weight: 400;    font-size: 15px;    margin: 0px 55px;    font-weight: bo;"> (*)You're about to experience a stress-free, quick & accurate migration. Just log in!</div>
   
    <form method="POST" class="form-horizontal">
      {% if error_message %}
      <span class="alert text-danger">{{error_message}}</span>
      <br>
      {% endif %}
      {% csrf_token %}
      {% if error_message2 %}
      <span class="alert text-danger">{{error_message2}}</span>
      <br>
      {% endif %}

      <br><br>
      <div class="form-group row ">
        <div class="col-md-6 text-right"><label for="email">Email:</label></div>
        <div class="col-md-6 text-left"><input type="text" name="email" placeholder="Your email"><span class="text-secondary"> (you will use it to login)</span> 
        </div>
        <br>
      </div>
      <div class="form-group row ">
        <div class="col-md-6 text-right"><label for="name">Your Name:</label></div>
        <div class="col-md-6 text-left"><input type="text" name="name" placeholder="Your name"></div>
        <br>
      </div>
      <div class="form-group row">
        <div class="col-md-6 text-right"><label for="password">Password:</label></div>
        <div class="col-md-6 text-left"><input type="password" name="pwd" placeholder="Password"></div>
        <br>
      </div>
      {% if error_message1 %}
      <span class="alert text-danger">{{error_message1}}</span>
      <br>
      {% endif %}
      <div class="form-group row">
        <div class="col-md-6 text-right"><label for="password">Repeat password:</label></div>
        <div class="col-md-6 text-left"><input type="password" name="repwd" placeholder="Repeat password"></div>
        <br>
      </div>
      <br>
      <div class="form-group button-panel">
        <div class="" style="text-align: center;">
            <button type="submit" name="submit" class="web-button web-button-default signup" style="padding: 0 50px">
              Sign Up
            </button>
        </div>
    </div>
    </form>
  </div>
  <div class ="hidden_if_phone">
    <br>
    <br>

    <br>
    <br>
    <br>
    <br>

  </div>
<div class="col-xs-12 text-center small">
    <label>* By signing in, you agree to our <a href="https://litextension.com/terms-conditions.html">Terms and Conditions</a>, <a href="https://litextension.com/privacy-policy.html">Private Policy</a>, <a href="https://litextension.com/gdpr-compliance.html">GDPR Compliance</a> and to receive LitExtension emails & updates of the migration process.</label>
</div>

{% endblock %}

main/templates/main/snake.html
<!DOCTYPE html>
<html>
<head>
    <title>Game-snake</title>
    <style>
        body {
            height: 100%;
            margin: 0;
            background: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        canvas {
            margin: 100px;
            background-color: #999999;
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <!-- tao box-game -->
    <canvas width="400" height="400" id="game"></canvas>
    <script>
        // gán box-game thành biến
        var canvas = document.getElementById('game');
        var context = canvas.getContext('2d');
        //giá trị 1 ô
        var grid = 16; // 25*25 ô
        // khởi tạo đối tượng rắn là 1 ô vuông
        var snake = {
            //vị trí của đầu rắn
            x: 160, 
            y: 160,
            
            //hướng di chuyển
            dx: grid, 
            dy: 0,

            cells: [],
            maxCells: 4
        };
        var count = 0;
        var apple = {
            x: random(1,25)*25,
            y: random(1,25)*25,
        };

        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min)) + min;
        }
        // game loop
        function loop() {
            //hàm này giống như setTimeout, sẽ gọi lại hàm loop khi loop thực thi xong
            requestAnimationFrame(loop);
            // game loop 10fps
            if (++count < 6) {
                return;
            }
            count = 0;
            context.clearRect(0, 0, canvas.width, canvas.height);
            snake.x += snake.dx; // mỗi loop rắn sẽ di chuyển thêm 1dx đơn vị
            snake.y += snake.dy;
            // khi snake đụng tường sẽ chạy lại từ edge đối diện
            if (snake.x < 0) {
                snake.x = canvas.width - grid;
            }
            else if (snake.x >= canvas.width) {
                snake.x = 0;
            }
            if (snake.y < 0) {
                snake.y = canvas.height - grid;
            }
            else if (snake.y >= canvas.height) {
                snake.y = 0;
            }
            // Phương thức unshift sẽ thêm một hoặc nhiều phần tử vào đầu mảng
            snake.cells.unshift({ x: snake.x, y: snake.y });
            // thêm 1 ô vuông phía trc thì phải remove 1 cái phía sau để snake move dc.
            if (snake.cells.length > snake.maxCells) {
                snake.cells.pop();
            }
            // draw apple
            context.fillStyle = 'red';
            context.fillRect(apple.x, apple.y, grid - 1, grid - 1);
            // draw snake
            context.fillStyle = 'green';
            snake.cells.forEach(function (cell, index) {
                context.fillRect(cell.x, cell.y, grid - 1, grid - 1);
                // snake ate apple
                if (cell.x === apple.x && cell.y === apple.y) {
                    snake.maxCells++;
                    apple.x = getRandomInt(0, 25) * grid;
                    apple.y = getRandomInt(0, 25) * grid;
                }
                // check va chạm khi rắn đụng đuôi
                for (var i = index + 1; i < snake.cells.length; i++) {
                    // va chạm thì reset game
                    if (cell.x === snake.cells[i].x && cell.y === snake.cells[i].y) {
                        snake.x = 160;
                        snake.y = 160;
                        snake.cells = [];
                        snake.maxCells = 4;
                        snake.dx = grid;
                        snake.dy = 0;
                        apple.x = getRandomInt(0, 25) * grid;
                        apple.y = getRandomInt(0, 25) * grid;
                    }
                }
            });
        }
        //bắt sự kiện bàn phím ấn xuống
        document.addEventListener('keydown', function (e) {
            // lọc sự kiện keydown để rắn không di ngược lại
            if (e.which === 37 && snake.dx === 0) {
                snake.dx = -grid;
                snake.dy = 0;
            }
            else if (e.which === 38 && snake.dy === 0) {
                snake.dy = -grid;
                snake.dx = 0;
            }
            else if (e.which === 39 && snake.dx === 0) {
                snake.dx = grid;
                snake.dy = 0;
            }
            else if (e.which === 40 && snake.dy === 0) {
                snake.dy = grid;
                snake.dx = 0;
            }
        });
        requestAnimationFrame(loop);
    </script>
</body>
</html>